# Generated by Django 5.2 on 2025-04-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('request_log', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='EndpointServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endpoint')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.server')),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='servers',
            field=models.ManyToManyField(through='core.EndpointServer', to='core.server'),
        ),
    ]
